import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

// The API contract lives in the web app; the backend keeps exact copies in src/contract:
//   frontend/src/types/index.ts        -> src/contract/types.ts        (request / response shapes)
//   frontend/src/domain/rules/*.ts     -> src/contract/rules/*.ts      (business rules both sides apply)
// The rules import only '@/types' (rewritten to '../types.js') and each other.
//   npm run contract:sync   copy them here (after changing them there)
//   npm run contract:check  fail when a copy is out of date (CI, before a commit)

const FRONTEND = resolve(import.meta.dirname, '../../frontend/src')
const CONTRACT = resolve(import.meta.dirname, '../src/contract')
const header = (from: string) => `// GENERATED by \`npm run contract:sync\` from frontend/src/${from}. Do not edit here.\n\n`

if (!existsSync(FRONTEND)) {
  console.error(`${FRONTEND} not found (the frontend lives next to the backend in this repository)`)
  process.exit(1)
}

/** target path (relative to src/contract) -> generated content */
function expected(): Map<string, string> {
  const files = new Map<string, string>()
  files.set('types.ts', header('types/index.ts') + readFileSync(`${FRONTEND}/types/index.ts`, 'utf8'))
  for (const name of readdirSync(`${FRONTEND}/domain/rules`).filter((f) => f.endsWith('.ts') && !f.endsWith('.spec.ts'))) {
    const source = readFileSync(`${FRONTEND}/domain/rules/${name}`, 'utf8').replaceAll("from '@/types'", "from '../types.js'")
    files.set(`rules/${name}`, header(`domain/rules/${name}`) + source)
  }
  return files
}

const read = (path: string) => (existsSync(path) ? readFileSync(path, 'utf8') : null)
const ruleFiles = () => (existsSync(`${CONTRACT}/rules`) ? readdirSync(`${CONTRACT}/rules`).map((f) => `rules/${f}`) : [])

const mode = process.argv[2]
const files = expected()
if (mode === 'sync') {
  rmSync(`${CONTRACT}/rules`, { recursive: true, force: true })
  mkdirSync(`${CONTRACT}/rules`, { recursive: true })
  for (const [path, content] of files) writeFileSync(`${CONTRACT}/${path}`, content)
  console.log(`contract synced -> ${CONTRACT} (${files.size} files)`)
} else if (mode === 'check') {
  const stale = [...files].filter(([path, content]) => read(`${CONTRACT}/${path}`) !== content).map(([path]) => path)
  const extra = ruleFiles().filter((path) => !files.has(path))
  if (stale.length || extra.length) {
    console.error(`src/contract is out of date (${[...stale, ...extra].join(', ')}): run \`npm run contract:sync\``)
    process.exit(1)
  }
  console.log('contract up to date')
} else {
  console.error('usage: tsx scripts/contract.ts sync|check')
  process.exit(2)
}
