import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

// The API contract's types live in the web app (frontend/src/types/index.ts); the backend keeps an
// exact copy in src/contract/types.ts.
//   npm run contract:sync   copy the web app's types here (after changing the contract there)
//   npm run contract:check  fail when the copy is out of date (CI, before a commit)

const SOURCE = resolve(import.meta.dirname, '../../frontend/src/types/index.ts')
const TARGET = resolve(import.meta.dirname, '../src/contract/types.ts')
const HEADER = '// GENERATED by `npm run contract:sync` from frontend/src/types/index.ts. Do not edit here.\n\n'

const mode = process.argv[2]
const source = HEADER + readFileSync(SOURCE, 'utf8')

if (mode === 'sync') {
  writeFileSync(TARGET, source)
  console.log(`contract synced -> ${TARGET}`)
} else if (mode === 'check') {
  let current = ''
  try {
    current = readFileSync(TARGET, 'utf8')
  } catch {
    // missing counts as out of date
  }
  if (current !== source) {
    console.error('src/contract/types.ts differs from frontend/src/types/index.ts: run `npm run contract:sync`')
    process.exit(1)
  }
  console.log('contract up to date')
} else {
  console.error('usage: tsx scripts/contract.ts sync|check')
  process.exit(2)
}
