// Builds src/plugins/tabler-icons.ts: the SVG of every Tabler icon the app uses, and nothing else.
// The app writes icons as icon="tabler:name"; this scans src/ for those names, so the bundle carries
// ~160 icons instead of the whole webfont (1.8 MB ttf). An unknown name fails here instead of showing
// an empty box at runtime. Runs before dev / build (npm run icons); `--check` only verifies the file.
import { readFileSync, readdirSync, statSync, writeFileSync, existsSync } from 'node:fs'
import { join, relative } from 'node:path'

const ROOT = new URL('..', import.meta.url).pathname
const SRC = join(ROOT, 'src')
const OUT = join(SRC, 'plugins', 'tabler-icons.ts')
const ICONS = join(ROOT, 'node_modules', '@tabler', 'icons', 'icons')

const files = (dir) =>
  readdirSync(dir).flatMap((name) => {
    const path = join(dir, name)
    return statSync(path).isDirectory() ? files(path) : /\.(vue|ts)$/.test(name) && path !== OUT ? [path] : []
  })

const used = new Map() // name -> first file using it
for (const file of files(SRC)) {
  for (const [, name] of readFileSync(file, 'utf8').matchAll(/tabler:([a-z0-9]+(?:-[a-z0-9]+)*)/g)) {
    if (!used.has(name)) used.set(name, relative(ROOT, file))
  }
}

const missing = []
const entries = [...used.keys()].sort().map((name) => {
  const filled = name.endsWith('-filled')
  const path = join(ICONS, filled ? 'filled' : 'outline', `${filled ? name.slice(0, -'-filled'.length) : name}.svg`)
  if (!existsSync(path)) {
    missing.push(`${name} (${used.get(name)})`)
    return ''
  }
  const body = readFileSync(path, 'utf8')
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>[\s\S]*$/, '')
    .replace(/<path stroke="none" d="M0 0h24v24H0z" fill="none"\s*\/>/, '') // Tabler's empty bounding box
    .replace(/\s*\n\s*/g, '')
  return `  '${name}': { body: '${body.replace(/'/g, "\\'")}'${filled ? ', filled: true' : ''} },`
})

if (missing.length) {
  console.error(`Unknown Tabler icon(s), see https://tabler.io/icons:\n  ${missing.join('\n  ')}`)
  process.exit(1)
}

const output = `// Generated by scripts/gen-icons.mjs from @tabler/icons: do not edit. Run \`npm run icons\`.
// Only the icons used in src/ (icon="tabler:name").

export const TABLER_ICONS: Record<string, { body: string; filled?: true }> = {
${entries.join('\n')}
}
`

if (process.argv.includes('--check')) {
  if (!existsSync(OUT) || readFileSync(OUT, 'utf8') !== output) {
    console.error('src/plugins/tabler-icons.ts is out of date: run `npm run icons`')
    process.exit(1)
  }
  console.log(`tabler icons up to date (${used.size})`)
} else {
  writeFileSync(OUT, output)
  console.log(`tabler icons: ${used.size} written to ${relative(ROOT, OUT)}`)
}
