// Demo data for defect.service.ts (the mock database is seeded with it on first use)
import type { Defect } from '@/types'
import { addDays, todayISO } from '@/utils/date'

const day = (n: number) => `${addDays(todayISO(), n)}T09:00:00Z`
export const SEED_DEFECTS: Defect[] = [
  {
    id: 'BUG-001',
    projectId: 'proj-1',
    title: 'Webhook ซ้ำพร้อมกันทำให้บันทึกรายการชำระเงินซ้ำ',
    severity: 'critical',
    status: 'retest',
    description: 'เมื่อธนาคารส่ง callback เดิมพร้อมกันหลาย request ระบบสร้าง transaction ซ้ำ',
    stepsToReproduce: '1. ชำระเงินสำเร็จ 1 รายการ\n2. ยิง Webhook payment.success เดิม 10 request พร้อมกันด้วย k6\n3. ตรวจตาราง transactions',
    expected: 'มีรายการเดียว',
    actual: 'มี 2 รายการ ยอดถูกบันทึกซ้ำ',
    caseId: 'TC-103',
    runId: 'run-1',
    stepNumber: 2,
    assignee: 'กิตติศักดิ์ พัฒนา (Dev Lead)',
    reportedBy: 'สมชาย ประเสริฐ (QA Lead)',
    externalKey: 'PAY-482',
    environment: 'Staging · v3.2.0-rc1',
    evidence: [],
    comments: [
      { by: 'กิตติศักดิ์ พัฒนา (Dev Lead)', at: day(-6), text: 'เพิ่ม Distributed lock ด้วย Redis แล้ว deploy ใน rc2' },
      { by: 'สมชาย ประเสริฐ (QA Lead)', at: day(-2), text: 'รอทดสอบซ้ำในรอบ Regression' },
    ],
    createdAt: day(-8),
    updatedAt: day(-2),
  },
  {
    id: 'BUG-002',
    projectId: 'proj-1',
    title: 'ข้อความ Error ไม่บอกเวลาที่ QR หมดอายุ',
    severity: 'minor',
    status: 'open',
    description: 'หน้าจอ QR หมดอายุแสดงแค่ "ทำรายการไม่สำเร็จ"',
    stepsToReproduce: '1. สร้าง QR\n2. รอ 15 นาที\n3. ดูหน้าจอ',
    expected: 'แสดง "QR หมดอายุ กรุณาสร้างใหม่"',
    actual: 'แสดง "ทำรายการไม่สำเร็จ"',
    caseId: 'TC-101-1',
    assignee: 'ธนากร สุขใจ (Backend API)',
    reportedBy: 'พิชญา ศรีสุข (Senior Tester)',
    environment: 'Staging',
    evidence: [],
    comments: [],
    createdAt: day(-5),
    updatedAt: day(-5),
  },
  {
    id: 'BUG-003',
    projectId: 'proj-1',
    title: 'DLQ ไม่ได้รับข้อความหลัง Retry ครบ 5 ครั้ง',
    severity: 'major',
    status: 'in_progress',
    description: 'ข้อความที่ retry ครบหายไปแทนที่จะเข้า Dead Letter Queue',
    stepsToReproduce: '1. ปิด endpoint ปลายทาง\n2. ส่ง Webhook\n3. รอ retry ครบ',
    expected: 'ข้อความอยู่ใน DLQ',
    actual: 'ไม่พบข้อความ',
    caseId: 'TC-104',
    assignee: 'ธนากร สุขใจ (Backend API)',
    reportedBy: 'สมชาย ประเสริฐ (QA Lead)',
    externalKey: 'PAY-490',
    environment: 'Staging',
    evidence: [],
    comments: [],
    createdAt: day(-4),
    updatedAt: day(-1),
  },
  {
    id: 'BUG-004',
    projectId: 'proj-1',
    title: 'ปุ่มดาวน์โหลดใบเสร็จตัดคำภาษาไทย',
    severity: 'trivial',
    status: 'closed',
    description: 'ข้อความบนปุ่มถูกตัดบนมือถือ',
    stepsToReproduce: 'เปิดหน้าใบเสร็จบน iPhone SE',
    expected: 'ข้อความครบ',
    actual: 'ถูกตัด',
    reportedBy: 'พิชญา ศรีสุข (Senior Tester)',
    evidence: [],
    comments: [],
    createdAt: day(-12),
    updatedAt: day(-9),
  },
]
