// GENERATED by `npm run contract:sync` from frontend/src/domain/rules/defect.ts. Do not edit here.

import type { Defect } from '../types.js'

/** still affects a release */
export const isOpenDefect = (d: Pick<Defect, 'status'>) => !['closed', 'rejected'].includes(d.status)
