// GENERATED by `npm run contract:sync` from frontend/src/domain/rules/document.ts. Do not edit here.

import type {
  Defect,
  DocCase,
  DocumentOptions,
  DocumentSnapshot,
  DocumentTemplate,
  DocumentType,
  Project,
  Requirement,
  TestCase,
  TestRun,
  UatDetails,
} from '../types.js'
import { isOpenDefect } from './defect.js'
import { casesForRequirement, compareRequirements, coverageStatus, requirementText, torCaseIds } from './requirement.js'
import { environmentOf } from './project.js'
import { RESULT_LABELS, RESULT_TONES, currentResultOf, latestEnvironmentResults } from './run.js'
import { STATUS_LABELS, STATUS_TONES, isOverdue } from './test-case.js'

/** the organisation's template until one is saved */
export const DEFAULT_TEMPLATE: DocumentTemplate = {
  companyName: 'บริษัท เทสต์พัลส์ เทคโนโลยี จำกัด',
  companyAddress: '999 อาคารดิจิทัล ชั้น 12 ถนนพระราม 9 กรุงเทพฯ 10310',
  logo: '',
  docNumberPattern: '{TYPE}-{KEY}-{YYYYMMDD}-{NN}',
  headerNote: 'เอกสารนี้จัดทำโดยระบบ TestPulse จากผลการทดสอบจริงในระบบ',
  footerNote: 'เอกสารภายใน · ห้ามเผยแพร่โดยไม่ได้รับอนุญาต',
  defaultSignatories: [
    { role: 'ผู้จัดทำ (ผู้ส่งมอบ)', position: 'QA Lead' },
    { role: 'ผู้ตรวจสอบ', position: 'Project Manager' },
    { role: 'ผู้อนุมัติ (ผู้รับมอบ)', position: 'Product Owner' },
  ],
}

/** what a document is made from: the project's data at generation time */
export interface SnapshotSources {
  project: Pick<Project, 'name' | 'key' | 'description' | 'targetDeadline' | 'environments'>
  /** every case of the project, archived ones too (a run still shows the ones it executed) */
  cases: TestCase[]
  /** the chosen run (options.runId), else the cases' current status is printed */
  run?: TestRun
  /** the project's runs: a UAT on a non-primary environment prints each case's latest result there */
  runs?: TestRun[]
  defects: Defect[]
  requirements: Requirement[]
}

const outcomeOf = (status: string): DocCase['outcome'] => (status === 'passed' || status === 'failed' || status === 'blocked' ? status : 'not_run')

const byId = (a: { id: string }, b: { id: string }) => a.id.localeCompare(b.id, undefined, { numeric: true })

/** the data a document prints, frozen when it is generated */
export function buildSnapshot(
  req: { type: DocumentType; options: DocumentOptions; uat?: UatDetails },
  { project, cases: projectCases, run, runs = [], defects: projectDefects, requirements: projectRequirements }: SnapshotSources,
  generatedAt = new Date().toISOString(),
): DocumentSnapshot {
  // archived cases are out of scope (lists, coverage)
  const allCases = projectCases.filter((c) => !c.archivedAt)
  const torOnly = !!req.options.torOnly
  const requirements = (torOnly ? projectRequirements.filter((r) => r.origin === 'tor') : projectRequirements).slice().sort(compareRequirements)
  // TOR only: the cases that test a TOR requirement (a run's deleted cases can't say, so they are left out)
  const torCases = torOnly ? torCaseIds(requirements, projectCases) : null
  // UAT on a chosen environment: its results (a non-primary one keeps its own), and only its server problems
  const env = req.type === 'uat' ? environmentOf(project, req.uat?.environmentId) : undefined
  const envResults = env && !env.primary && !run ? latestEnvironmentResults(runs, env.id, project) : null
  const defects = env ? projectDefects.filter((d) => d.cause !== 'environment' || d.environmentId === env.id) : projectDefects

  let cases: DocCase[]
  if (run) {
    cases = run.results.map((r) => {
      const tc = r.caseDeleted ? undefined : projectCases.find((c) => c.id === r.caseId)
      return {
        id: r.caseDeleted ? `${r.caseId} (ลบแล้ว)` : r.caseId,
        name: r.caseName,
        parentId: tc?.parentId,
        requirement: tc ? requirementText(tc, projectRequirements) : '',
        testScenario: tc?.testScenario ?? '',
        prerequisite: tc?.prerequisite ?? '',
        priority: r.priority,
        steps: r.steps,
        expectedResults: tc?.expectedResults ?? '',
        outcome: outcomeOf(r.status),
        result: RESULT_LABELS[r.status],
        resultTone: RESULT_TONES[r.status],
        actualResults: r.actualResults,
        executedBy: r.executedBy,
        executedAt: r.executedAt,
        stepResults: r.stepResults,
        evidence: [...r.evidence, ...r.stepResults.flatMap((s) => s.evidence)],
        defectIds: r.defectIds,
      }
    })
  } else if (envResults) {
    cases = allCases.map((tc) => {
      const latest = currentResultOf(tc, envResults)
      const r = latest && runs.find((x) => x.id === latest.runId)?.results.find((x) => x.caseId === tc.id)
      return {
        id: tc.id,
        name: tc.name,
        parentId: tc.parentId,
        requirement: requirementText(tc, projectRequirements),
        testScenario: tc.testScenario,
        prerequisite: tc.prerequisite,
        priority: tc.priority,
        steps: tc.steps,
        expectedResults: tc.expectedResults,
        outcome: outcomeOf(latest?.status ?? 'untested'),
        result: RESULT_LABELS[latest?.status ?? 'untested'],
        resultTone: RESULT_TONES[latest?.status ?? 'untested'],
        actualResults: r?.actualResults ?? '',
        executedBy: latest?.executedBy,
        executedAt: latest?.executedAt,
        stepResults: r?.stepResults,
        evidence: r ? [...r.evidence, ...r.stepResults.flatMap((x) => x.evidence)] : [],
        defectIds: defects.filter((d) => d.caseId === tc.id && !d.caseDeleted).map((d) => d.id),
      }
    })
  } else {
    cases = allCases.map((tc) => ({
      id: tc.id,
      name: tc.name,
      parentId: tc.parentId,
      requirement: requirementText(tc, projectRequirements),
      testScenario: tc.testScenario,
      prerequisite: tc.prerequisite,
      priority: tc.priority,
      steps: tc.steps,
      expectedResults: tc.expectedResults,
      outcome: outcomeOf(tc.status),
      result: STATUS_LABELS[tc.status],
      resultTone: STATUS_TONES[tc.status],
      actualResults: tc.actualResults,
      executedBy: tc.executedBy,
      executedAt: tc.executedAt,
      evidence: [...tc.expectedImages, ...tc.actualImages],
      defectIds: defects.filter((d) => d.caseId === tc.id && !d.caseDeleted).map((d) => d.id),
    }))
  }
  if (torCases) cases = cases.filter((c) => torCases.has(c.id))
  if (!req.options.includeSubCases) cases = cases.filter((c) => !c.parentId)
  if (!req.options.includeEvidence)
    cases = cases.map((c) => ({ ...c, evidence: [], stepResults: c.stepResults?.map((s) => ({ ...s, evidence: [] })) }))
  cases.sort(byId)

  const count = (o: DocCase['outcome']) => cases.filter((c) => c.outcome === o).length
  const passed = count('passed')
  const failed = count('failed')
  const blocked = count('blocked')
  const caseIds = new Set(cases.map((c) => c.id))
  /** defects of the printed cases, of deleted ones, or of none */
  const inScope = (d: Defect) => !d.caseId || d.caseDeleted || caseIds.has(d.caseId)
  const openDefects = defects.filter((d) => isOpenDefect(d) && inScope(d) && d.cause !== 'environment')
  const openServer = defects.filter((d) => isOpenDefect(d) && inScope(d) && d.cause === 'environment')
  const overdue = allCases.filter((c) => caseIds.has(c.id) && isOverdue(c))

  const risks = [
    failed && `มีเคสไม่ผ่าน ${failed} เคส`,
    blocked && `มีเคสที่ทดสอบไม่ได้ (Blocked) ${blocked} เคส`,
    overdue.length && `มีเคสเลยกำหนดส่งมอบ ${overdue.length} เคส`,
    openDefects.length && `มี Defect ที่ยังเปิดอยู่ ${openDefects.length} รายการ`,
    openServer.length && `มีปัญหาด้าน Server / Environment ที่ยังเปิดอยู่ ${openServer.length} รายการ`,
  ].filter(Boolean) as string[]

  return {
    generatedAt,
    project: { name: project.name, key: project.key, description: project.description, targetDeadline: project.targetDeadline },
    run: run && {
      name: run.name,
      round: run.round,
      type: run.type,
      environment: run.environment,
      build: run.build,
      plannedStart: run.plannedStart,
      plannedEnd: run.plannedEnd,
      startedAt: run.startedAt,
      completedAt: run.completedAt,
    },
    environment: env && { name: env.name, primary: env.primary },
    summary: {
      total: cases.length,
      passed,
      failed,
      blocked,
      notRun: cases.length - passed - failed - blocked,
      passRate: cases.length ? (passed / cases.length) * 100 : 0,
    },
    cases,
    defects: (req.options.includeDefects ? defects.filter(inScope) : []).map(
      ({ id, title, severity, status, caseId, caseDeleted, assignee, externalKey, cause, environment }) => ({
        id,
        cause,
        environment,
        title,
        severity,
        status,
        caseId: caseId && caseDeleted ? `${caseId} (ลบแล้ว)` : caseId,
        assignee,
        externalKey,
      }),
    ),
    requirements:
      req.options.includeTraceability || req.type === 'rtm'
        ? requirements.map((r) => {
            const linked = casesForRequirement(r, allCases)
            return { code: r.code, title: r.title, torClause: r.torClause, caseIds: linked.map((c) => c.id), coverage: coverageStatus(linked) }
          })
        : [],
    risks,
  }
}

/**
 * Release gatekeeper: why a UAT sign-off can't be made from this snapshot (null = it can).
 * Open risks rule out full acceptance and must be acknowledged for any other decision.
 */
export function uatBlock(uat: UatDetails | undefined, risks: string[]): string | null {
  if (!uat || !risks.length) return null
  if (uat.decision === 'accepted') return `ไม่สามารถตรวจรับแบบสมบูรณ์ได้: ${risks.join(', ')}`
  return uat.riskAcknowledged ? null : 'ต้องยืนยันรับทราบความเสี่ยงก่อนสร้างเอกสาร UAT'
}
