// GENERATED by `npm run contract:sync` from frontend/src/domain/rules/requirement.ts. Do not edit here.

import type { CoverageStatus, Requirement, TestCase } from '../types.js'

/** the text starts with the whole code: "REQ-PAY-1: …" mentions REQ-PAY-1 but not REQ-PAY-10 */
const mentionsCode = (text: string, code: string) => text.startsWith(code) && !/^[\w-]/.test(text.slice(code.length))

/** linked explicitly; cases without links (imported / legacy) fall back to text that starts with the code */
const isLinked = (req: Requirement, tc: TestCase) =>
  tc.projectId === req.projectId &&
  (tc.requirementIds?.length ? tc.requirementIds.includes(req.id) : mentionsCode(tc.requirement?.trim() ?? '', req.code))

export const casesForRequirement = (req: Requirement, cases: TestCase[]): TestCase[] => cases.filter((c) => isLinked(req, c))

export const requirementsForCase = (tc: TestCase, requirements: Requirement[]): Requirement[] => requirements.filter((r) => isLinked(r, tc))

/**
 * What a case shows as its requirement: the linked records ("CODE: title", always current),
 * then the case's own note when it adds something. Unlinked cases show their free text.
 */
export function requirementText(tc: TestCase, requirements: Requirement[]): string {
  const linked = requirementsForCase(tc, requirements)
  const note = tc.requirement?.trim() ?? ''
  if (!linked.length) return note
  const lines = linked.map((r) => `${r.code}: ${r.title}`)
  // text auto-filled from a link, or legacy text naming the code, only repeats the link
  if (note && !linked.some((r) => mentionsCode(note, r.code))) lines.push(note)
  return lines.join('\n')
}

const natural = (a: string, b: string) => a.localeCompare(b, undefined, { numeric: true })

/** list order: TOR requirements by clause (4.2.9 before 4.2.10), then the additional ones, each by code */
export function compareRequirements(a: Requirement, b: Requirement): number {
  if (a.origin !== b.origin) return a.origin === 'tor' ? -1 : 1
  return (a.origin === 'tor' && natural(a.torClause ?? '', b.torClause ?? '')) || natural(a.code, b.code)
}

/** the ids of the cases that test a TOR requirement: linked themselves, or a sub-case of one that is */
export function torCaseIds(requirements: Requirement[], cases: TestCase[]): Set<string> {
  const tor = requirements.filter((r) => r.origin === 'tor')
  const linked = new Set(cases.filter((c) => tor.some((r) => isLinked(r, c))).map((c) => c.id))
  for (const c of cases) if (c.parentId && linked.has(c.parentId)) linked.add(c.id)
  return linked
}

export function coverageStatus(cases: TestCase[]): CoverageStatus {
  if (!cases.length) return 'not_covered'
  if (cases.some((c) => c.status === 'failed' || c.status === 'blocked')) return 'failed'
  if (cases.every((c) => c.status === 'passed')) return 'passed'
  if (cases.some((c) => c.status === 'passed' || c.status === 'in_progress')) return 'in_progress'
  return 'not_run'
}
