// GENERATED by `npm run contract:sync` from frontend/src/domain/rules/run.ts. Do not edit here.

import type { EnvironmentResult, Project, ResultStatus, RunResult, StepResult, TestCase, TestRun, Tone } from '../types.js'
import { primaryEnvironment } from './project.js'

/** how a result is named and coloured (UI, documents) */
export const RESULT_LABELS: Record<ResultStatus, string> = {
  passed: 'Pass',
  failed: 'Fail',
  blocked: 'Blocked',
  skipped: 'Skip',
  untested: 'ยังไม่ทดสอบ',
}

export const RESULT_TONES: Record<ResultStatus, Tone> = {
  passed: 'success',
  failed: 'error',
  blocked: 'caution',
  skipped: 'secondary',
  untested: 'secondary',
}

/** overall case result from its step results: any fail > any block > all pass/skip */
export function deriveResult(steps: StepResult[]): ResultStatus {
  if (!steps.length || steps.every((s) => s.status === 'untested')) return 'untested'
  if (steps.some((s) => s.status === 'failed')) return 'failed'
  if (steps.some((s) => s.status === 'blocked')) return 'blocked'
  if (steps.some((s) => s.status === 'untested')) return 'untested'
  return steps.every((s) => s.status === 'skipped') ? 'skipped' : 'passed'
}

export function runCounts(run: TestRun): Record<ResultStatus, number> & { total: number; executed: number; passRate: number } {
  const c = { passed: 0, failed: 0, blocked: 0, skipped: 0, untested: 0 } as Record<ResultStatus, number>
  run.results.forEach((r) => c[r.status]++)
  const total = run.results.length
  return { ...c, total, executed: total - c.untested, passRate: total ? (c.passed / total) * 100 : 0 }
}

/** snapshot of a case for a run */
export const resultFor = (tc: TestCase, assignee?: string): RunResult => ({
  caseId: tc.id,
  caseName: tc.name,
  caseVersion: tc.version,
  priority: tc.priority,
  steps: tc.steps,
  assignee: assignee ?? tc.assignedTo,
  status: 'untested',
  stepResults: tc.steps.map((s) => ({ stepId: s.id, status: 'untested', actual: '', evidence: [] })),
  actualResults: '',
  evidence: [],
  defectIds: [],
  notes: '',
})

/** the environment a run is on (runs made before environments were on the primary one) */
export const runEnvironmentId = (run: Pick<TestRun, 'environmentId'>, project: Pick<Project, 'environments'>): string =>
  run.environmentId || primaryEnvironment(project).id

/**
 * Why a verdict in this run must not change the case's current status, or null when it may.
 * The case status is "the latest result for the current spec on the primary environment": a run on
 * another environment, a closed run, a deleted case, a result for an older version or a run that a
 * newer one on the same environment has superseded only keep their history.
 * Used by the server (saveResult) and by Execute to explain it.
 */
export function caseSyncBlock(
  run: TestRun,
  result: RunResult,
  tc: TestCase | undefined,
  allRuns: TestRun[],
  project: Pick<Project, 'environments'>,
): string | null {
  if (result.caseDeleted) return 'Test Case นี้ถูกลบแล้ว'
  if (run.status === 'completed') return 'รอบนี้ปิดแล้ว'
  if (!tc) return 'ไม่พบ Test Case'
  if (tc.archivedAt) return 'Test Case นี้อยู่ในคลังเก็บ'
  const primary = primaryEnvironment(project)
  const env = runEnvironmentId(run, project)
  if (env !== primary.id) return `ผลบน ${run.environment} เก็บแยกไว้ ไม่เปลี่ยนสถานะหลักของเคส (สถานะหลักมาจาก ${primary.name})`
  if (tc.version !== result.caseVersion) return `ผลนี้ทดสอบกับ ${result.caseVersion} แต่เคสเป็น ${tc.version} แล้ว`
  const newer = allRuns.find(
    (r) =>
      r.projectId === run.projectId &&
      r.id !== run.id &&
      runEnvironmentId(r, project) === env &&
      r.createdAt > run.createdAt &&
      r.results.some((x) => x.caseId === result.caseId && !x.caseDeleted && x.status !== 'untested'),
  )
  return newer ? `มีผลที่ใหม่กว่าใน ${newer.name} รอบที่ ${newer.round}` : null
}

/**
 * Each case's latest result on one environment, by case id: the newest run on it with a verdict for
 * the case wins (the same "latest result" the primary environment's status follows). `runs` are the
 * project's runs.
 */
export function latestEnvironmentResults(
  runs: TestRun[],
  environmentId: string,
  project: Pick<Project, 'environments'>,
): Map<string, EnvironmentResult> {
  const latest = new Map<string, EnvironmentResult>()
  const onEnv = runs.filter((r) => runEnvironmentId(r, project) === environmentId).sort((a, b) => b.createdAt.localeCompare(a.createdAt))
  for (const run of onEnv)
    for (const r of run.results) {
      if (r.caseDeleted || r.status === 'untested' || latest.has(r.caseId)) continue
      latest.set(r.caseId, {
        environmentId,
        status: r.status,
        runId: run.id,
        runName: run.name,
        round: run.round,
        caseVersion: r.caseVersion,
        executedBy: r.executedBy,
        executedAt: r.executedAt,
      })
    }
  return latest
}

/** the case's result on an environment, when it was tested on the case's current version (an older spec's result no longer says anything) */
export const currentResultOf = (tc: Pick<TestCase, 'id' | 'version'>, results: Map<string, EnvironmentResult>): EnvironmentResult | undefined => {
  const r = results.get(tc.id)
  return r && r.caseVersion === tc.version ? r : undefined
}
