import { defineComponent, h } from 'vue'
import type { IconSet, ThemeDefinition } from 'vuetify'
import { createVuetify } from 'vuetify'
import { aliases, mdi } from 'vuetify/iconsets/mdi-svg'
import { TABLER_ICONS } from './tabler-icons'

// Tabler Icons as inline SVG -> use as  icon="tabler:home". Only the icons used in src/ are bundled
// (src/plugins/tabler-icons.ts, generated by `npm run icons`); same markup as Vuetify's own SVG icons.
const TablerIcon = defineComponent({
  name: 'TablerIcon',
  props: { icon: { type: [String, Array, Object, Function], required: true }, tag: { type: String, required: true } },
  // a real component (not a plain function), so every attribute VIcon passes reaches the element
  setup(props) {
    return () => {
      const icon = TABLER_ICONS[props.icon as string]
      return h(props.tag, [
        h('svg', {
          class: 'v-icon__svg',
          xmlns: 'http://www.w3.org/2000/svg',
          viewBox: '0 0 24 24',
          role: 'img',
          'aria-hidden': 'true',
          // outline icons are strokes: .v-icon__svg sets fill: currentColor, so turn it off inline
          style: icon?.filled ? undefined : { fill: 'none' },
          stroke: icon?.filled ? 'none' : 'currentColor',
          'stroke-width': 2,
          'stroke-linecap': 'round',
          'stroke-linejoin': 'round',
          innerHTML: icon?.body ?? '',
        }),
      ])
    }
  },
})

const tabler: IconSet = { component: TablerIcon as unknown as IconSet['component'] }

// ---------------------------------------------------------------------------
// Colors: taken from "Colors - Blue Version.png" in the Fox kit
// ---------------------------------------------------------------------------
const light: ThemeDefinition = {
  dark: false,
  colors: {
    background: '#FAFAFA', // page background (estimated from screenshots)
    surface: '#FFFFFF',
    'on-surface': '#11142D', // main text

    primary: '#1E4DB7',
    secondary: '#67757C',
    info: '#1A9BFC',
    accent: '#0BB2FB',
    success: '#39CB7F',
    warning: '#FEC90F',
    error: '#FC4B6C',
    // TestPulse: orange between warning and error (blocked cases, high priority, churn)
    caution: '#FB8C3C',

    // extra tokens -> usable as  text-muted / bg-light-primary  etc.
    muted: '#777E89',
    'light-primary': '#E4EAF6', // primary @ 12% on white
    'light-info': '#E4F3FF',
    'light-success': '#E7F9F0',
    'light-warning': '#FFF9E2',
    'light-error': '#FFE9ED',
    'light-caution': '#FFF0E5',
  },
  variables: {
    'border-color': '#11142D',
    'border-opacity': 0.12,
  },
}

// NOTE: the Fox screenshots only show the light UI. This dark theme is an
// estimate so the moon toggle in the header has something to switch to.
const dark: ThemeDefinition = {
  dark: true,
  colors: {
    background: '#0E1020',
    surface: '#151833',
    'on-surface': '#E6E8F2',

    primary: '#4C7BEA',
    secondary: '#8A97A0',
    info: '#1A9BFC',
    accent: '#0BB2FB',
    success: '#39CB7F',
    warning: '#FEC90F',
    error: '#FC4B6C',
    caution: '#FF9F5A',

    muted: '#9AA1B0',
    'light-primary': '#1E2A55',
    'light-info': '#14304A',
    'light-success': '#16372B',
    'light-warning': '#3A3213',
    'light-error': '#40202A',
    'light-caution': '#3E2A1A',
  },
  variables: {
    'border-color': '#FFFFFF',
    'border-opacity': 0.12,
  },
}

// Shared look for every text-like field
const field = {
  variant: 'outlined',
  density: 'comfortable',
  color: 'primary',
  hideDetails: 'auto',
} as const

export default createVuetify({
  theme: {
    defaultTheme: 'light',
    themes: { light, dark },
  },

  // Component defaults = change the look once, applies everywhere
  defaults: {
    VBtn: { elevation: 0, rounded: 'lg' },
    VChip: { label: true },

    VTextField: field,
    VTextarea: field,
    VSelect: field,
    VAutocomplete: field,
    VCombobox: field,
    VFileInput: field,

    VCheckbox: { color: 'primary', density: 'comfortable', hideDetails: 'auto' },
    VRadioGroup: { color: 'primary', hideDetails: 'auto' },
    VSwitch: { color: 'primary', density: 'comfortable', hideDetails: 'auto' },
    VSlider: { color: 'info', thumbColor: 'primary', trackSize: 6, hideDetails: true },
    VRangeSlider: { color: 'info', thumbColor: 'primary', trackSize: 6, hideDetails: true },

    VList: { nav: true },

    VAvatar: { variant: 'tonal' },
    VBadge: { color: 'error', dotColor: 'error' },
    VTooltip: { location: 'top' },
    VMenu: { offset: 8 },
    VDialog: { maxWidth: 640, scrollable: true },
    VDataTable: { hover: true, density: 'comfortable' },
    VDivider: { opacity: 0.08 },
    VTabs: { color: 'primary' },
    VSnackbar: { location: 'top right', timeout: 2500 },
    VFooter: { color: 'transparent' },
    VAppBar: { flat: true },
  },

  icons: {
    // Vuetify's own icons ($close, $expand, checkboxes …) as MDI SVG paths (no icon font);
    // the app's icons are Tabler: icon="tabler:home"
    defaultSet: 'mdi',
    aliases,
    sets: { mdi, tabler },
  },
})
